# Dependencies
markdown:         kramdown
highlighter:      rouge


# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
color:                '#0064a6'
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile]
permalink:            /:title/


# Site meta
title:                'UWC Docs'
tagline:              'Change is a minimalist Jekyll theme built by Connor Bär.'
keywords:             'connor, baer, bear, designer, developer, traveller, design, code, jekyll, change, theme, for hire'
description:          'Change is a minimalist Jekyll theme built by Connor Bär.'
url:                  http://docs.uwc.io
baseurl:              ''
logo:                 /assets/icons/apple-icon-144x144.png
twitter:
  username:           connor_baer

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

author:
  name:               Connor Bär
  url:                http://connorbaer.io
  email:              hello@connorbaer.io
  twitter:            connor_baer

version:              1.0.0


github:
  repo:               https://github.com/uwc/uwc-docs
